#==================== Tomcat Setting =====================#
server:
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
  port: 8081
#==================== spring Setting =====================#
spring:
  datasource:
    druid:
      username: root
      password: 47218382
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ojdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      max-active: 50
      min-idle: 10
      initial-size: 10
      max-wait: 10
      default-auto-commit: true
#  mvc:
#    view:
#      prefix: /
#      suffix: .html
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 30MB
  http:
    encoding:
      charset: UTF-8
#==================== thymeleaf Setting =====================#
  thymeleaf:
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:templates/
    suffix: .html
    cache: false

#==================== mybatis Setting =====================#
mybatis:
  config-location: classpath:mybatis.config.xml
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.oj.gkuoj.entity

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#==================== logging Setting =====================#
logging:
  config: classpath:logback.xml

#==================== project Setting =====================#
project:
  isDebug: true